function Hd = EIIR170(sampleRate)

%IIR170 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 25-Dec-2018 16:13:17

% Elliptic Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
%Fs = 48000;  % Sampling Frequency
Fs = sampleRate;

Fpass = 170;     % Passband Frequency
Fstop = 170.2;     % Stopband Frequency
Apass = 0.01;    % Passband Ripple (dB)
Astop = 100;     % Stopband Attenuation (dB)
match = 'both';  % Band to match exactly

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'ellip', 'MatchExactly', match);
% [EOF]
