function Hd = KFIR170(sampleRate)
%KFIR170 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 25-Dec-2018 17:28:25

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
%Fs = 48000;  % Sampling Frequency
Fs = sampleRate;

N    = 100;      % Order
Fc   = 170;      % Cutoff Frequency
flag = 'scale';  % Sampling Flag
Beta = 3;        % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
